# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-15 07:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HotKeyStat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='num',
            field=models.CharField(max_length=10, verbose_name='Block number block in the group'),
        ),
        migrations.AlterField(
            model_name='block',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HotKeyStat.Block', verbose_name='Parent block'),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='org_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HotKeyStat.Organizations', verbose_name='Paternal organization'),
        ),
    ]
