# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-15 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotKeyStat', '0003_result_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='date_result',
            field=models.DateField(null=True, verbose_name='Date of result'),
        ),
    ]
