# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-24 08:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('HotKeyStat', '0004_auto_20180215_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='date_reg',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Date registartion'),
        ),
        migrations.AlterField(
            model_name='result',
            name='correct',
            field=models.PositiveIntegerField(default=0, verbose_name='count of correct answers'),
        ),
        migrations.AlterField(
            model_name='result',
            name='date_result',
            field=models.DateField(default=datetime.datetime(2018, 2, 24, 8, 28, 58, 293088, tzinfo=utc), null=True, verbose_name='Date of result'),
        ),
        migrations.AlterField(
            model_name='result',
            name='key_count',
            field=models.PositiveIntegerField(default=0, verbose_name='count of keys'),
        ),
        migrations.AlterField(
            model_name='result',
            name='total',
            field=models.PositiveIntegerField(default=0, verbose_name='count of total answers'),
        ),
    ]
