# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-24 11:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('HotKeyStat', '0005_auto_20180224_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='correct',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='count of correct answers'),
        ),
        migrations.AlterField(
            model_name='result',
            name='date_result',
            field=models.DateField(default=datetime.datetime(2018, 2, 24, 11, 29, 50, 769627, tzinfo=utc), null=True, verbose_name='Date of result'),
        ),
        migrations.AlterField(
            model_name='result',
            name='total',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='count of total answers'),
        ),
    ]
