# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-24 11:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('HotKeyStat', '0006_auto_20180224_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='number',
            new_name='number_block',
        ),
        migrations.AlterField(
            model_name='result',
            name='date_result',
            field=models.DateField(default=datetime.datetime(2018, 2, 24, 11, 55, 2, 843113, tzinfo=utc), null=True, verbose_name='Date of result'),
        ),
    ]
