# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-21 10:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('HotKeyStat', '0007_auto_20180224_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='rank',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Rank of the learner'),
        ),
        migrations.AlterField(
            model_name='result',
            name='date_result',
            field=models.DateField(default=datetime.datetime(2018, 3, 21, 10, 12, 55, 901704, tzinfo=utc), null=True, verbose_name='Date of result'),
        ),
    ]
